import os


MODEL_ID = "amazon.nova-2-sonic-v1:0"
NOVA_MAX_TOKENS = int(os.getenv("NOVA_MAX_TOKENS", "1024"))
NOVA_TOP_P = float(os.getenv("NOVA_TOP_P", "0.9"))
NOVA_TEMPERATURE = float(os.getenv("NOVA_TEMPERATURE", "0.0"))

# 音声認識の言語設定 (例: "en-US", "ja-JP", None=自動検出)
TRANSCRIPT_LANGUAGE = os.getenv("TRANSCRIPT_LANGUAGE", None)

TRANSLATION_MODEL_ID_DEFAULT = "anthropic.claude-haiku-4-5-20251001-v1:0"
TRANSLATION_MODEL_ID = os.getenv("TRANSLATION_MODEL_ID", TRANSLATION_MODEL_ID_DEFAULT)
TRANSLATION_MODEL_ID_FALLBACK_DEFAULT = "us.anthropic.claude-haiku-4-5-20251001-v1:0"
TRANSLATION_MODEL_ID_FALLBACK = os.getenv(
    "TRANSLATION_MODEL_ID_FALLBACK", TRANSLATION_MODEL_ID_FALLBACK_DEFAULT
)
TRANSLATION_MAX_TOKENS = int(os.getenv("TRANSLATION_MAX_TOKENS", "400"))
TRANSLATION_DEBOUNCE_SECONDS = float(os.getenv("TRANSLATION_DEBOUNCE_SECONDS", "0.4"))
TRANSLATION_MIN_INTERVAL_SECONDS = float(os.getenv("TRANSLATION_MIN_INTERVAL_SECONDS", "0.6"))
TRANSLATION_MAX_BATCH_CHARS = int(os.getenv("TRANSLATION_MAX_BATCH_CHARS", "1200"))

CATCHUP_MODEL_ID_DEFAULT = "us.anthropic.claude-haiku-4-5-20251001-v1:0"
CATCHUP_MODEL_ID = os.getenv("CATCHUP_MODEL_ID", CATCHUP_MODEL_ID_DEFAULT)
CATCHUP_MODEL_ID_FALLBACK = os.getenv("CATCHUP_MODEL_ID_FALLBACK", CATCHUP_MODEL_ID_DEFAULT)
CATCHUP_MAX_TOKENS = int(os.getenv("CATCHUP_MAX_TOKENS", "350"))
CATCHUP_MIN_INTERVAL_SECONDS = float(os.getenv("CATCHUP_MIN_INTERVAL_SECONDS", "15"))
CATCHUP_LOG_MAX_ITEMS = int(os.getenv("CATCHUP_LOG_MAX_ITEMS", "200"))
CATCHUP_LOG_MAX_SECONDS = int(os.getenv("CATCHUP_LOG_MAX_SECONDS", "1800"))
CATCHUP_MAX_INPUT_CHARS = int(os.getenv("CATCHUP_MAX_INPUT_CHARS", "6000"))

MEETING_ASSIST_MODEL_ID_DEFAULT = TRANSLATION_MODEL_ID_DEFAULT
MEETING_ASSIST_MODEL_ID = os.getenv("MEETING_ASSIST_MODEL_ID", TRANSLATION_MODEL_ID)
MEETING_ASSIST_MODEL_ID_FALLBACK_DEFAULT = TRANSLATION_MODEL_ID_FALLBACK_DEFAULT
MEETING_ASSIST_MODEL_ID_FALLBACK = os.getenv(
    "MEETING_ASSIST_MODEL_ID_FALLBACK", TRANSLATION_MODEL_ID_FALLBACK
)
MEETING_ASSIST_MAX_TOKENS = int(os.getenv("MEETING_ASSIST_MAX_TOKENS", "450"))
MEETING_ASSIST_MIN_INTERVAL_SECONDS = float(os.getenv("MEETING_ASSIST_MIN_INTERVAL_SECONDS", "45"))
MEETING_ASSIST_WINDOW_SECONDS = int(os.getenv("MEETING_ASSIST_WINDOW_SECONDS", "600"))
MEETING_ASSIST_MAX_INPUT_CHARS = int(os.getenv("MEETING_ASSIST_MAX_INPUT_CHARS", "8000"))

AWS_REGION_DEFAULT = "ap-northeast-1"

# Bedrock側ストリーム寿命(8分)手前で更新
RENEW_SECONDS = 7 * 60 + 45  # 7m45s
# プロキシタイムアウト回避用キープアライブ間隔
KEEPALIVE_SECONDS = 30
